language: node_js
node_js:
- 6.9.5
branches:
  only:
  - hexo
before_install:
- npm install -g yarn
- npm install -g hexo-cli gulp
install:
- yarn
script:
- hexo clean
- hexo generate
- gulp
after_success:
- git config --global user.name "Larry Nung"
- git config --global user.email "larrynung@hotmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy
env:
  global:
    secure: h8seWg250yPzJGOiFf1cVBHKnjlxBapOgXSP4lXEiFtqWaupYzsJSdo8qeqjMYQ41yHlIakuwP5edj8TCZYPlwbzQw6JEYYpUnJVRLMPq2ZfZS6kjqB4+M6JgF/RXC10EjvYAfAzfyJpVVGMgSPyA4tvPMMhSEccNI4wECMUeg0=
