language: node_js
node_js:
- '0.12'
branches:
  only:
  - hexo
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- hexo generate
after_success:
- git config --global user.name "Larry Nung"
- git config --global user.email "larrynung@hotmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy --silent
dd:
  secure: Fb6ignxOEhy6V/XIJyuRL3a/S3Ia3KRrT/EN3ohi+SRYhxS2s5MT30TXbQbc3iz6/TjfZzpBcA3MYDvx5a5DtB8crtPe5ofmJqYIhyioAH3ObZKvW3Ty5StqYI4wTXY+5FZI+cKA/4gVU7pTdLBNx4erLIXSzkRRgM1q7FZRdNE=
